---
## Part A: NumPy Array Operations (30 points)

### Question 1: Revenue Simulation (10 points)

You run a small Nigerian market stall selling 4 products. Simulate 30 days of business:

**Requirements:**
1. Generate daily sales quantities for 4 products (use normal distribution)
   - Product A: mean=50, std=10
   - Product B: mean=30, std=5
   - Product C: mean=70, std=15
   - Product D: mean=40, std=8
2. Set random seed to your favorite number
3. Ensure no negative quantities (clip at 0)
4. Print the shape and first 5 days

**Deliverable:** Create a 30×4 NumPy array called `daily_sales`

In [1]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate sales data with specified distributions
product_a = np.random.normal(50, 10, 30)
product_b = np.random.normal(30, 5, 30)
product_c = np.random.normal(70, 15, 30)
product_d = np.random.normal(40, 8, 30)

# Stack arrays to create 30x4 array
daily_sales = np.column_stack([product_a, product_b, product_c, product_d])

# Ensure no negative quantities (clip at 0)
daily_sales = np.clip(daily_sales, 0, None)

# Display results
print("Shape of daily_sales:", daily_sales.shape)
print("\nFirst 5 days of sales:")
print(daily_sales[:5])

Shape of daily_sales: (30, 4)

First 5 days of sales:
[[54.96714153 26.99146694 62.81238643 40.77662039]
 [48.61735699 39.26139092 67.21511535 47.74915992]
 [56.47688538 29.93251388 53.40497539 34.38357525]
 [65.23029856 24.71144536 52.05690064 37.37870283]
 [47.65846625 34.11272456 82.18788734 36.86313477]]


### Question 2: Financial Analysis (10 points)

Using the `daily_sales` array from Q1:

**Calculate:**
1. Total sales for each product over 30 days
2. Average daily sales per product
3. The day with maximum total sales (across all products)
4. How many days had total sales above the 30-day average?
5. Standard deviation of sales for each product

**Deliverable:** Print all results with clear labels

In [2]:
# Question 2: Financial Analysis

# 1. Total sales for each product over 30 days
total_sales = np.sum(daily_sales, axis=0)
print("Total sales for each product over 30 days:")
print(f"Product A: {total_sales[0]:.2f}")
print(f"Product B: {total_sales[1]:.2f}")
print(f"Product C: {total_sales[2]:.2f}")
print(f"Product D: {total_sales[3]:.2f}")

# 2. Average daily sales per product
average_daily_sales = np.mean(daily_sales, axis=0)
print("\nAverage daily sales per product:")
print(f"Product A: {average_daily_sales[0]:.2f}")
print(f"Product B: {average_daily_sales[1]:.2f}")
print(f"Product C: {average_daily_sales[2]:.2f}")
print(f"Product D: {average_daily_sales[3]:.2f}")

# 3. The day with maximum total sales (across all products)
daily_totals = np.sum(daily_sales, axis=1)
max_day = np.argmax(daily_totals)
print(f"\nDay with maximum total sales: Day {max_day + 1} with {daily_totals[max_day]:.2f} units")

# 4. How many days had total sales above the 30-day average?
overall_average = np.mean(daily_totals)
days_above_average = np.sum(daily_totals > overall_average)
print(f"\nDays with total sales above 30-day average: {days_above_average} days")

# 5. Standard deviation of sales for each product
std_dev = np.std(daily_sales, axis=0)
print("\nStandard deviation of sales for each product:")
print(f"Product A: {std_dev[0]:.2f}")
print(f"Product B: {std_dev[1]:.2f}")
print(f"Product C: {std_dev[2]:.2f}")
print(f"Product D: {std_dev[3]:.2f}")

Total sales for each product over 30 days:
Product A: 1443.56
Product B: 881.83
Product C: 2105.80
Product D: 1195.14

Average daily sales per product:
Product A: 48.12
Product B: 29.39
Product C: 70.19
Product D: 39.84

Day with maximum total sales: Day 23 with 209.94 units

Days with total sales above 30-day average: 18 days

Standard deviation of sales for each product:
Product A: 8.85
Product B: 4.58
Product C: 14.63
Product D: 7.15


### Question 3: Price & Revenue Calculation (10 points)

Your products have these prices: [200, 350, 150, 280] NGN

**Tasks:**
1. Calculate daily revenue (price × quantity for each product)
2. Calculate total revenue over 30 days
3. Apply a promotional discount:
   - Days 1-5: 15% off all products
   - Days 15-20: 10% off Product A and B only
   - Other days: no discount
4. Calculate total revenue with discounts
5. How much discount did you give away?

**Hint:** Use boolean indexing and broadcasting

In [3]:
# Question 3: Price & Revenue Calculation
prices = np.array([200, 350, 150, 280])

# 1. Calculate daily revenue (price × quantity for each product)
daily_revenue = daily_sales * prices
print("Daily Revenue for first 5 days:")
print(daily_revenue[:5])

# 2. Calculate total revenue over 30 days
total_revenue_no_discount = np.sum(daily_revenue)
print(f"\nTotal revenue without discount: ₦{total_revenue_no_discount:.2f}")

# 3. Apply promotional discount
discount_rate = np.zeros(30)
# Days 1-5: 15% off all products
discount_rate[0:5] = 0.15
# Days 15-20: 10% off Product A and B only
discount_rate[14:20] = 0.10

# Create a discount array (30 x 4) where day 15-20 has 10% for products A,B only
discount_array = np.zeros_like(daily_revenue, dtype=float)
discount_array[0:5, :] = 0.15  # 15% off all products for days 1-5
discount_array[14:20, 0:2] = 0.10  # 10% off Product A and B for days 15-20

# 4. Calculate revenue with discounts
revenue_with_discount = daily_revenue * (1 - discount_array)
total_revenue_with_discount = np.sum(revenue_with_discount)
print(f"Total revenue with discounts: ₦{total_revenue_with_discount:.2f}")

# 5. How much discount was given away?
total_discount_given = total_revenue_no_discount - total_revenue_with_discount
print(f"\nTotal discount given away: ₦{total_discount_given:.2f}")
print(f"Discount percentage: {(total_discount_given/total_revenue_no_discount*100):.2f}%")

Daily Revenue for first 5 days:
[[10993.42830602  9447.0134286   9421.85796485 11417.45371054]
 [ 9723.47139766 13741.48682289 10082.26730251 13369.76477879]
 [11295.3770762  10476.37985671  8010.74630849  9627.40106971]
 [13046.05971282  8649.00587433  7808.53509582 10466.03679162]
 [ 9531.69325055 11939.45359618 12328.18310039 10321.67773698]]

Total revenue without discount: ₦1247858.97
Total revenue with discounts: ₦1205394.33

Total discount given away: ₦42464.64
Discount percentage: 3.40%


---
## Part B: Pandas Data Analysis (50 points)

### Question 4: Load and Explore Your Dataset (10 points)

**Task:** Find a dataset relevant to your problem domain, or use one of the provided datasets.

**Requirements:**
1. Load the dataset using Pandas
2. Display basic information:
   - Number of rows and columns
   - Column names and data types
   - First 10 rows
   - Statistical summary
   - Check for missing values
3. Write 2-3 sentences describing what this dataset contains

**Deliverable:** Load data into a DataFrame called `df` and provide the exploration

In [4]:
import pandas as pd

# Load the dataset
df = pd.read_csv('nigerian_market_prices.csv')

# Display basic information
print("Dataset Shape: {} rows × {} columns".format(df.shape[0], df.shape[1]))
print("\nColumn Names and Data Types:")
print(df.dtypes)
print("\nFirst 10 rows:")
print(df.head(10))
print("\nStatistical Summary:")
print(df.describe())
print("\nMissing Values:")
print(df.isnull().sum())

# Description of dataset
print("\n" + "="*50)
print("DATASET DESCRIPTION:")
print("="*50)
print("""
The Nigerian market prices dataset contains pricing information for various products 
in local Nigerian markets. This dataset captures market dynamics and pricing trends 
across different product categories, helping us understand price variations and 
market conditions in Nigeria's commercial landscape.
""")

Dataset Shape: 120 rows × 5 columns

Column Names and Data Types:
state       object
product     object
price        int64
quantity     int64
date        object
dtype: object

First 10 rows:
   state product  price  quantity        date
0  Lagos  Tomato    250        45  2024-01-15
1  Lagos   Onion    320        38  2024-01-15
2  Lagos  Pepper    450        28  2024-01-15
3  Lagos    Rice    520        65  2024-01-15
4  Lagos   Beans    380        42  2024-01-15
5  Lagos  Garlic    400        22  2024-01-15
6   Kano  Tomato    180        52  2024-01-15
7   Kano   Onion    260        45  2024-01-15
8   Kano  Pepper    380        32  2024-01-15
9   Kano    Rice    480        70  2024-01-15

Statistical Summary:
            price    quantity
count  120.000000  120.000000
mean   354.250000   40.933333
std     92.535821   13.556439
min    175.000000   18.000000
25%    283.750000   30.000000
50%    362.500000   40.000000
75%    401.250000   48.000000
max    530.000000   72.000000

Missing Va

### Question 5: Data Filtering & Selection (10 points)

Using your loaded dataset:

**Tasks:**
1. Select 3 columns of interest and display first 10 rows
2. Filter data based on a numeric condition (e.g., price > some_value)
3. Filter data based on a categorical condition (e.g., state == 'Lagos')
4. Combine two conditions using AND (&) or OR (|)
5. Display the shape of each filtered dataset

**Deliverable:** Show 4 different filtered views of your data

In [5]:
# Question 5: Data Filtering & Selection

# 1. Select 3 columns of interest and display first 10 rows
print("1. Three columns of interest (first 10 rows):")
selected_cols = df.iloc[:, :3]  # Select first 3 columns
print(selected_cols.head(10))
print(f"Shape: {selected_cols.shape}\n")

# 2. Filter data based on a numeric condition
# Find products with price above median
median_price = df['price'].median()
filter1 = df[df['price'] > median_price]
print(f"2. Products with price above median ({median_price:.2f}):")
print(filter1.head())
print(f"Shape: {filter1.shape}\n")

# 3. Filter data based on a categorical condition
# Filter by state
filter2 = df[df['state'] == 'Lagos']
print(f"3. Filtered by state = Lagos:")
print(filter2.head())
print(f"Shape: {filter2.shape}\n")

# 4. Combine two conditions using AND (&)
filter3 = df[(df['price'] > median_price) & (df['state'] == 'Lagos')]
print(f"4. Combined filter - Lagos with price above ₦{median_price:.2f}:")
print(filter3.head())
print(f"Shape: {filter3.shape}\n")

1. Three columns of interest (first 10 rows):
   state product  price
0  Lagos  Tomato    250
1  Lagos   Onion    320
2  Lagos  Pepper    450
3  Lagos    Rice    520
4  Lagos   Beans    380
5  Lagos  Garlic    400
6   Kano  Tomato    180
7   Kano   Onion    260
8   Kano  Pepper    380
9   Kano    Rice    480
Shape: (120, 3)

2. Products with price above median (362.50):
   state product  price  quantity        date
2  Lagos  Pepper    450        28  2024-01-15
3  Lagos    Rice    520        65  2024-01-15
4  Lagos   Beans    380        42  2024-01-15
5  Lagos  Garlic    400        22  2024-01-15
8   Kano  Pepper    380        32  2024-01-15
Shape: (60, 5)

3. Filtered by state = Lagos:
   state product  price  quantity        date
0  Lagos  Tomato    250        45  2024-01-15
1  Lagos   Onion    320        38  2024-01-15
2  Lagos  Pepper    450        28  2024-01-15
3  Lagos    Rice    520        65  2024-01-15
4  Lagos   Beans    380        42  2024-01-15
Shape: (24, 5)

4. Combined f

### Question 6: Aggregation & Grouping (15 points)

Using your dataset:

**Tasks:**
1. Group by a categorical column and calculate mean of a numeric column
2. Group by a categorical column and calculate multiple statistics (min, max, mean, sum)
3. Create a cross-tabulation or pivot table (if applicable)
4. Find the top 5 records by some criterion
5. Calculate at least one percentage or ratio

**Deliverable:** Perform 5 different aggregations/groupings

In [6]:
# Question 6: Aggregation & Grouping

# 1. Group by state and calculate mean
print("1. Group by state and calculate mean:")
grouped_mean = df.groupby('state')[['price', 'quantity']].mean()
print(grouped_mean)

# 2. Group by state and calculate multiple statistics
print("\n2. Multiple statistics per state:")
grouped_stats = df.groupby('state')[['price', 'quantity']].agg(['min', 'max', 'mean', 'sum'])
print(grouped_stats)

# 3. Pivot table
print("\n3. Pivot table by product and state:")
pivot_table = pd.pivot_table(df, values='price', index='product', columns='state', aggfunc='mean')
print(pivot_table)

# 4. Top 5 records by price
print("\n4. Top 5 most expensive products:")
top_5 = df.nlargest(5, 'price')[['state', 'product', 'price', 'quantity']]
print(top_5)

# 5. Calculate percentage of total quantity by state
print("\n5. Percentage of total quantity by state:")
df_temp = df.copy()
total_qty = df_temp['quantity'].sum()
qty_by_state = df_temp.groupby('state')['quantity'].sum()
percentage_by_state = (qty_by_state / total_qty * 100).round(2)
print(percentage_by_state)

1. Group by state and calculate mean:
             price   quantity
state                        
Abuja   364.166667  36.250000
Kano    334.166667  44.458333
Lagos   389.583333  39.125000
Oyo     334.166667  43.416667
Rivers  349.166667  41.416667

2. Multiple statistics per state:
       price                        quantity                     
         min  max        mean   sum      min max       mean   sum
state                                                            
Abuja    215  510  364.166667  8740       18  60  36.250000   870
Kano     175  490  334.166667  8020       23  72  44.458333  1067
Lagos    245  530  389.583333  9350       20  67  39.125000   939
Oyo      185  480  334.166667  8020       24  70  43.416667  1042
Rivers   195  500  349.166667  8380       22  64  41.416667   994

3. Pivot table by product and state:
state    Abuja   Kano  Lagos    Oyo  Rivers
product                                    
Beans    362.5  342.5  382.5  332.5   352.5
Garlic   382.5  352

### Question 7: Data Transformation (15 points)

Using your dataset:

**Tasks:**
1. Create a new column based on a calculation (e.g., total = price × quantity)
2. Create a categorical column based on numeric ranges (e.g., 'Low', 'Medium', 'High')
3. Sort data by 2 or more columns
4. Calculate a rolling or cumulative statistic (if time-series data)
5. Handle any missing values (if present) using appropriate methods

**Deliverable:** Show your transformed dataset with new columns

In [7]:
# Question 7: Data Transformation

df_transformed = df.copy()

# 1. Create a new column based on calculation (revenue = price × quantity)
df_transformed['revenue'] = df_transformed['price'] * df_transformed['quantity']
print("1. New calculated column 'revenue' (first 5 rows):")
print(df_transformed[['price', 'quantity', 'revenue']].head())

# 2. Create a categorical column based on numeric ranges
df_transformed['price_category'] = pd.cut(df_transformed['price'], 
                                           bins=[0, 250, 375, 530], 
                                           labels=['Low', 'Medium', 'High'])
print("\n2. Categorical column 'price_category':")
print(df_transformed[['price', 'price_category']].head(10))
print("\nPrice category distribution:")
print(df_transformed['price_category'].value_counts())

# 3. Sort data by price (descending) then quantity (descending)
print("\n3. Sorted data by price and quantity (first 10 rows):")
sorted_df = df_transformed.sort_values(by=['price', 'quantity'], ascending=[False, False]).head(10)
print(sorted_df[['state', 'product', 'price', 'quantity']])

# 4. Calculate cumulative sum and rolling mean for quantity by state
df_transformed['cumulative_qty'] = df_transformed.groupby('state')['quantity'].cumsum()
df_transformed['rolling_mean_qty'] = df_transformed.groupby('state')['quantity'].transform(
    lambda x: x.rolling(window=3, min_periods=1).mean()
)
print("\n4. Cumulative and rolling statistics (first 10 rows):")
print(df_transformed[['state', 'quantity', 'cumulative_qty', 'rolling_mean_qty']].head(10))

# 5. Handle missing values (check if any exist)
print("\n5. Missing values handling:")
missing_before = df_transformed.isnull().sum().sum()
print(f"Missing values before: {missing_before}")
# Use ffill() and bfill() instead of method parameter for numeric columns
numeric_cols = df_transformed.select_dtypes(include=['number']).columns
df_transformed[numeric_cols] = df_transformed[numeric_cols].ffill().bfill().fillna(0)
missing_after = df_transformed.isnull().sum().sum()
print(f"Missing values after: {missing_after}")

print("\nTransformed dataset shape:", df_transformed.shape)
print(f"New columns added: {[col for col in df_transformed.columns if col not in df.columns]}")

1. New calculated column 'revenue' (first 5 rows):
   price  quantity  revenue
0    250        45    11250
1    320        38    12160
2    450        28    12600
3    520        65    33800
4    380        42    15960

2. Categorical column 'price_category':
   price price_category
0    250            Low
1    320         Medium
2    450           High
3    520           High
4    380           High
5    400           High
6    180            Low
7    260         Medium
8    380           High
9    480           High

Price category distribution:
price_category
Medium    55
High      47
Low       18
Name: count, dtype: int64

3. Sorted data by price and quantity (first 10 rows):
      state product  price  quantity
93    Lagos    Rice    530        61
33    Lagos    Rice    525        63
3     Lagos    Rice    520        65
63    Lagos    Rice    515        67
105   Abuja    Rice    510        54
45    Abuja    Rice    505        56
15    Abuja    Rice    500        58
111  Rivers    

---
## Part C: Insights & Problem Domain (20 points)

### Question 8: Domain-Specific Analysis (20 points)

**Task:** Answer 3 specific questions about your dataset that are relevant to your problem domain.

**Requirements:**
1. State each question clearly
2. Write code to answer it using NumPy/Pandas
3. Provide interpretation of results (2-3 sentences per question)
4. Create at least one visualization (optional but encouraged)

**Example questions:**
- Healthcare: "What's the distribution of patient ages across clinics?"
- Agriculture: "Which crop has the most price volatility across regions?"
- Education: "What percentage of students score above 70% in each subject?"
- Business: "Which product generates the most revenue per region?"

**Deliverable:** 3 questions + code + interpretations

#### Question 8a: What is the distribution of prices across the market?

What is the distribution of prices across the market and which price range is most common?

In [8]:
# Question 8a: Price distribution analysis
# Reload the original dataset to ensure fresh data
df_q8 = pd.read_csv('nigerian_market_prices.csv')
price_col = df_q8['price']

# Calculate statistics
print("Price Distribution Analysis:")
print(f"Minimum price: ₦{price_col.min():.2f}")
print(f"Maximum price: ₦{price_col.max():.2f}")
print(f"Mean price: ₦{price_col.mean():.2f}")
print(f"Median price: ₦{price_col.median():.2f}")
print(f"Standard deviation: ₦{price_col.std():.2f}")

# Create price bins
df_analysis = df_q8.copy()
df_analysis['price_bin'] = pd.cut(price_col, bins=5)

# Count prices in each bin
print("\nPrice range distribution:")
price_dist = df_analysis['price_bin'].value_counts().sort_index()
print(price_dist)

# Find most common price range
most_common_idx = price_dist.argmax()
most_common_range = price_dist.index[most_common_idx]
print(f"\nMost common price range: {most_common_range}")
print(f"Number of products: {price_dist.iloc[most_common_idx]}")

Price Distribution Analysis:
Minimum price: ₦175.00
Maximum price: ₦530.00
Mean price: ₦354.25
Median price: ₦362.50
Standard deviation: ₦92.54

Price range distribution:
price_bin
(174.645, 246.0]    17
(246.0, 317.0]      20
(317.0, 388.0]      45
(388.0, 459.0]      16
(459.0, 530.0]      22
Name: count, dtype: int64

Most common price range: (317.0, 388.0]
Number of products: 45


**Interpretation:**

The price distribution analysis reveals the central tendency and spread of market prices. The mean and median values indicate where most products are priced, while the standard deviation shows the variability in pricing. By identifying the most common price range, we can understand consumer preferences and market positioning. This information is crucial for pricing strategies and identifying market opportunities in different price segments.

#### Question 8b: How do products compare in terms of price volatility?

Which product category or type has the highest price volatility, and what does this tell us about market conditions?

In [ ]:
# Question 8b: Price volatility analysis
# Reload the original dataset
df_q8b = pd.read_csv('nigerian_market_prices.csv')
price_col = df_q8b['price']

# Calculate coefficient of variation (volatility measure)
mean_price = price_col.mean()
std_price = price_col.std()
coef_variation = (std_price / mean_price) * 100

print("Price Volatility Analysis:")
print(f"Coefficient of Variation: {coef_variation:.2f}%")

# Analyze by state
volatility_by_state = df_q8b.groupby('state')['price'].apply(
    lambda x: (x.std() / x.mean() * 100) if x.mean() != 0 else 0
).sort_values(ascending=False)

print(f"\nPrice volatility by state:")
print(volatility_by_state)

most_volatile = volatility_by_state.idxmax()
print(f"\nMost volatile state: {most_volatile} (CV: {volatility_by_state.iloc[0]:.2f}%)")
least_volatile = volatility_by_state.idxmin()
print(f"Most stable state: {least_volatile} (CV: {volatility_by_state.iloc[-1]:.2f}%)")

**Interpretation:**

Price volatility indicates market stability and predictability. High volatility suggests price fluctuations due to supply-demand imbalances, seasonal factors, or external shocks, making it risky for both consumers and sellers. Products with low volatility are more stable and predictable, which is favorable for planning and budgeting. Understanding these patterns helps traders anticipate price changes and make informed purchasing and selling decisions.

#### Question 8c: What are the key statistical insights about market data?

What are the main statistical insights and outliers in the market data that could influence business decisions?

In [9]:
# Question 8c: Statistical insights and outliers
# Reload the original dataset
df_q8c = pd.read_csv('nigerian_market_prices.csv')
price_col = df_q8c['price']

# Calculate quartiles and IQR
Q1 = price_col.quantile(0.25)
Q3 = price_col.quantile(0.75)
IQR = Q3 - Q1

print("Statistical Insights:")
print(f"Q1 (25th percentile): ₦{Q1:.2f}")
print(f"Q3 (75th percentile): ₦{Q3:.2f}")
print(f"Interquartile Range: ₦{IQR:.2f}")

# Identify outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (price_col < lower_bound) | (price_col > upper_bound)
num_outliers = outliers.sum()

print(f"\nOutlier Analysis:")
print(f"Lower bound: ₦{lower_bound:.2f}")
print(f"Upper bound: ₦{upper_bound:.2f}")
print(f"Number of outliers: {num_outliers}")
print(f"Percentage of outliers: {(num_outliers/len(df_q8c)*100):.2f}%")

if num_outliers > 0:
    print(f"\nOutlier values:")
    print(df_q8c[outliers][['state', 'product', 'price', 'quantity']].head())
else:
    print("\nNo outliers detected based on IQR method")

# Calculate skewness manually
mean = price_col.mean()
std = price_col.std()
n = len(price_col)
skewness = ((price_col - mean) ** 3).sum() / (n * std ** 3)

print(f"\nSkewness: {skewness:.3f}")
if abs(skewness) < 0.5:
    print("Distribution is fairly symmetric")
elif skewness > 0:
    print("Distribution is right-skewed (positive skew)")
else:
    print("Distribution is left-skewed (negative skew)")

Statistical Insights:
Q1 (25th percentile): ₦283.75
Q3 (75th percentile): ₦401.25
Interquartile Range: ₦117.50

Outlier Analysis:
Lower bound: ₦107.50
Upper bound: ₦577.50
Number of outliers: 0
Percentage of outliers: 0.00%

No outliers detected based on IQR method

Skewness: -0.086
Distribution is fairly symmetric


**Interpretation:**

Statistical insights like quartiles, IQR, and skewness help us understand the data distribution and identify exceptional cases. Outliers represent unusual prices that deviate significantly from the norm—these could be premium products, data errors, or special circumstances. Understanding the skewness tells us whether prices tend to cluster toward the lower or higher end. These insights guide pricing strategies, help detect data quality issues, and inform risk management decisions in the market.

---
## Bonus Challenge (Optional, +10 points)

### Bonus: Advanced Analysis

Choose ONE of the following challenges:

**Option A: Multi-dataset Merge**
- Load a second related dataset
- Merge/join the two datasets appropriately
- Perform analysis that requires both datasets
- Provide insights from the combined data

**Option B: Time Series Analysis**
- Use a time-series dataset (or convert your data to time-indexed)
- Calculate daily/weekly/monthly aggregations
- Identify trends or patterns over time
- Find anomalies or outliers

**Option C: Custom Aggregation Function**
- Write a custom function to apply to grouped data
- Use `.apply()` or `.agg()` with your function
- Solve a problem that requires custom logic
- Explain why built-in functions weren't sufficient

**Deliverable:** Complete ONE option with code and explanation

In [ ]:
# BONUS CHALLENGE: Option C - Custom Aggregation Function

# Reload the original dataset
df_bonus = pd.read_csv('nigerian_market_prices.csv')

# Define a custom function for custom aggregation
def calculate_price_metrics(group):
    """
    Custom function to calculate comprehensive price metrics for a group
    Returns min, max, mean, median, and range
    """
    return pd.Series({
        'min_price': group.min(),
        'max_price': group.max(),
        'mean_price': group.mean(),
        'median_price': group.median(),
        'price_range': group.max() - group.min(),
        'count': len(group)
    })

# Apply custom function using groupby and apply
bonus_result = df_bonus.groupby('state')['price'].apply(calculate_price_metrics)
print("BONUS Challenge Results - Custom Aggregation by State:")
print(bonus_result)

print("\n" + "="*60)
print("EXPLANATION:")
print("="*60)
print("""
Custom aggregation functions are needed when built-in pandas functions cannot 
provide the specific insights required. In this case, we created a function that 
calculates multiple complementary metrics (min, max, mean, median, range, count) 
in a single operation. This is more efficient than calling separate aggregation 
functions and provides a unified view of the data characteristics for each group. 
The custom function returns a Series, making it compatible with pandas' apply() method.
""")

---
## Reflection (Required)

Answer these questions:

1. **What was the most challenging part of this assignment?**
   
   The most challenging part was understanding boolean indexing and applying discount logic across multiple dimensions. Working with 2D arrays and applying conditional operations based on both day and product type required careful planning of array shapes and broadcasting logic to ensure the discounts were applied correctly.

2. **What NumPy/Pandas concept do you still find confusing?**
   
   While I've become more comfortable with these tools, advanced indexing (fancy indexing) and the interaction between different data types can still be tricky. Also, understanding when to use different aggregation methods and how they behave with missing data requires careful attention to documentation and testing.

3. **How will you use NumPy/Pandas in your problem domain project?**
   
   NumPy and Pandas will be essential for data cleaning, transformation, and analysis in my problem domain. I'll use NumPy for numerical computations and statistical calculations, and Pandas for handling structured data, performing groupby operations, and generating reports that support data-driven decision-making in market analysis and business intelligence.

4. **What additional data would help you solve your problem?**
   
   To make the analysis more comprehensive, it would be helpful to have temporal data (dates) to analyze trends over time, seasonal patterns, and price movements. Additionally, having categorical data about product types, locations, and suppliers would enable deeper segmentation analysis and allow for more targeted insights based on specific market segments.

---
## Submission Checklist

Before submitting, ensure:
- [ ] All code cells run without errors
- [ ] All questions are answered
- [ ] Code has comments explaining logic
- [ ] Results are clearly labeled
- [ ] Interpretations are provided for Question 8
- [ ] Reflection questions are answered
- [ ] Notebook is saved with your name in the filename

**Good luck! 🚀**