## 1. Why NumPy? Performance Comparison

Let's see why NumPy is essential for data science.

In [ ]:
import numpy as np
import time

# Create large dataset
size = 1_000_000

# Python list
python_list = list(range(size))

# NumPy array
numpy_array = np.arange(size)

# Time Python list operation
start = time.time()
result_list = [x * 2 for x in python_list]
python_time = time.time() - start

# Time NumPy operation
start = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list: {python_time:.4f} seconds")
print(f"NumPy array: {numpy_time:.4f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x faster!")

## 2. Creating NumPy Arrays

There are many ways to create arrays. Let's explore the most common methods.

In [15]:
# From Python list
prices = np.array([100, 150, 200, 175, 225])
print("From list:", prices)
print("Data type:", prices.dtype)
print()

# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)
print()

# Array of ones
ones = np.ones((3, 4))  # 3 rows, 4 columns
print("Ones (3x4):")
print(ones)
print()

# Range of values
range_array = np.arange(0, 10, 2)  # start, stop, step
print("Range (0 to 10, step 2):", range_array)
print()

# Linearly spaced values
linear = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print("Linear space (0 to 1, 5 values):", linear)

From list: [100 150 200 175 225]
Data type: int64

Zeros: [0. 0. 0. 0. 0.]

Ones (3x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range (0 to 10, step 2): [0 2 4 6 8]

Linear space (0 to 1, 5 values): [0.   0.25 0.5  0.75 1.  ]


### Nigerian Market Example: Creating Price Data

In [16]:
# Simulate market prices for 5 Nigerian states
states = ['Lagos', 'Kano', 'Abuja', 'Rivers', 'Oyo']

tomato_prices = np.array([250, 180, 220, 200, 190])  # Naira per kg

print("State-wise Tomato Prices (NGN/kg):")
for state, price in zip(states, tomato_prices):
    print(f"{state:10s}: ₦{price}")

State-wise Tomato Prices (NGN/kg):
Lagos     : ₦250
Kano      : ₦180
Abuja     : ₦220
Rivers    : ₦200
Oyo       : ₦190


## 3. Random Number Generation

Essential for simulations and generating sample data.

In [ ]:
# Set seed for reproducibility
np.random.seed(42)

# Random floats between 0 and 1
random_floats = np.random.rand(5)
print("Random floats:", random_floats)
print()

# Random integers
random_ints = np.random.randint(100, 300, size=10)  # 10 prices between 100-300
print("Random prices (100-300 NGN):", random_ints)
print()

# Normal distribution (mean=200, std=30)
normal_prices = np.random.normal(200, 30, size=20)
print("Normally distributed prices:")
print(normal_prices)
print(f"Mean: ₦{normal_prices.mean():.2f}")
print(f"Std Dev: ₦{normal_prices.std():.2f}")

## 4. Array Indexing and Slicing

Accessing elements in arrays is similar to Python lists, but more powerful.

In [ ]:
# Create sample data: prices over 10 days
daily_prices = np.array([200, 210, 205, 215, 220, 218, 225, 230, 228, 235])

print("All prices:", daily_prices)
print()

# Single element (0-indexed)
print("First day price:", daily_prices[0])
print("Last day price:", daily_prices[-1])
print()

# Slicing
print("First 3 days:", daily_prices[0:3])
print("Last 3 days:", daily_prices[-3:])
print("Every other day:", daily_prices[::2])
print()

# Boolean indexing (very powerful!)
high_prices = daily_prices > 220
print("Days with price > 220:", high_prices)
print("Actual high prices:", daily_prices[high_prices])
print()

# Fancy indexing (select specific indices)
selected_days = [0, 3, 7]
print(f"Prices on days {selected_days}:", daily_prices[selected_days])

## 5. Multi-dimensional Arrays

Working with 2D arrays (matrices) - common in data science.

In [17]:
# Create 2D array: 4 products x 5 markets
# Rows = products (Tomato, Onion, Pepper, Rice)
# Columns = markets (Lagos, Kano, Abuja, Rivers, Oyo)

market_prices = np.array([
    [250, 180, 220, 200, 190],  # Tomato
    [300, 250, 280, 270, 260],  # Onion
    [400, 350, 380, 370, 360],  # Pepper
    [500, 450, 480, 470, 460]   # Rice
])

print("Market Prices Array (4 products x 5 markets):")
print(market_prices)
print(f"Shape: {market_prices.shape}")
print(f"Number of dimensions: {market_prices.ndim}")
print(f"Total elements: {market_prices.size}")
print()

# Indexing 2D arrays
print("Tomato price in Lagos (row 0, col 0):", market_prices[0, 0])
print("Rice prices in all markets (row 3):", market_prices[3, :])
print("All prices in Abuja (col 2):", market_prices[:, 2])
print()

# Slicing 2D arrays
print("First 2 products in first 3 markets:")
print(market_prices[0:2, 0:3])

Market Prices Array (4 products x 5 markets):
[[250 180 220 200 190]
 [300 250 280 270 260]
 [400 350 380 370 360]
 [500 450 480 470 460]]
Shape: (4, 5)
Number of dimensions: 2
Total elements: 20

Tomato price in Lagos (row 0, col 0): 250
Rice prices in all markets (row 3): [500 450 480 470 460]
All prices in Abuja (col 2): [220 280 380 480]

First 2 products in first 3 markets:
[[250 180 220]
 [300 250 280]]


## 6. Array Operations and Broadcasting

NumPy's magic: operations on entire arrays without loops!

In [ ]:
prices = np.array([100, 150, 200, 175, 225])

# Arithmetic with scalars (broadcasting)
print("Original prices:", prices)
print("After 10% increase:", prices * 1.1)
print("Add ₦20 to all:", prices + 20)
print("Convert to dollars (÷1500):", prices / 1500)
print()

# Array-to-array operations
day1_prices = np.array([100, 150, 200, 175, 225])
day2_prices = np.array([105, 148, 205, 180, 220])

price_change = day2_prices - day1_prices
percent_change = (price_change / day1_prices) * 100

print("Day 1 prices:", day1_prices)
print("Day 2 prices:", day2_prices)
print("Price change:", price_change)
print("Percent change:", percent_change)

### Broadcasting with 2D Arrays

In [ ]:
# Apply 10% tax to all products in all markets
tax_rate = 0.10
prices_with_tax = market_prices * (1 + tax_rate)

print("Original prices:")
print(market_prices)
print()
print("Prices with 10% tax:")
print(prices_with_tax)
print()

# Different tax rates per product
tax_rates = np.array([0.05, 0.07, 0.10, 0.02])  # Tax per product
print("Tax rates per product:", tax_rates)
print()

# Broadcasting: (4,) array × (4, 5) array
# NumPy automatically expands tax_rates to match shape
prices_with_varying_tax = market_prices * (1 + tax_rates[:, np.newaxis])
print("Prices with varying tax rates:")
print(prices_with_varying_tax)

## 7. Statistical Operations

NumPy has built-in functions for common statistical operations.

In [18]:
# Generate sample data: daily sales for a week
np.random.seed(42)
daily_sales = np.random.randint(50, 150, size=7)

print("Daily sales (units):", daily_sales)
print()

# Basic statistics
print(f"Mean: {daily_sales.mean():.2f} units/day")
print(f"Median: {np.median(daily_sales):.2f} units")
print(f"Std Dev: {daily_sales.std():.2f} units")
print(f"Min: {daily_sales.min()} units")
print(f"Max: {daily_sales.max()} units")
print(f"Total: {daily_sales.sum()} units")
print()

# Which day had max sales?
max_day = daily_sales.argmax()
print(f"Best day: Day {max_day + 1} with {daily_sales[max_day]} units")

Daily sales (units): [101 142  64 121 110  70 132]

Mean: 105.71 units/day
Median: 110.00 units
Std Dev: 27.51 units
Min: 64 units
Max: 142 units
Total: 740 units

Best day: Day 2 with 142 units


### Statistics on 2D Arrays (Axis Operations)

In [ ]:
# Using our market_prices array
print("Market Prices:")
print(market_prices)
print()

# Overall statistics
print(f"Overall average price: ₦{market_prices.mean():.2f}")
print()

# Statistics per product (across markets) - axis=1
avg_per_product = market_prices.mean(axis=1)
products = ['Tomato', 'Onion', 'Pepper', 'Rice']
print("Average price per product (across all markets):")
for product, avg in zip(products, avg_per_product):
    print(f"{product:8s}: ₦{avg:.2f}")
print()

# Statistics per market (across products) - axis=0
avg_per_market = market_prices.mean(axis=0)
markets = ['Lagos', 'Kano', 'Abuja', 'Rivers', 'Oyo']
print("Average price per market (across all products):")
for market, avg in zip(markets, avg_per_market):
    print(f"{market:8s}: ₦{avg:.2f}")

## 8. Basic Linear Algebra Operations

Essential operations for machine learning and data analysis.

In [19]:
# Matrix multiplication
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print()

# Element-wise multiplication
print("Element-wise multiplication (A * B):")
print(A * B)
print()

# Matrix multiplication (dot product)
print("Matrix multiplication (A @ B):")
print(A @ B)
print()

# Transpose
print("Transpose of A:")
print(A.T)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise multiplication (A * B):
[[ 5 12]
 [21 32]]

Matrix multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]


### Practical Example: Calculating Total Revenue

In [ ]:
# Quantities sold per product per market (4 products x 5 markets)
quantities = np.array([
    [100, 120, 90, 110, 95],   # Tomato (kg)
    [80, 90, 70, 85, 75],       # Onion (kg)
    [50, 60, 45, 55, 48],       # Pepper (kg)
    [150, 140, 160, 155, 145]   # Rice (kg)
])

# Prices (same as market_prices)
# Revenue = price × quantity (element-wise)
revenue = market_prices * quantities

print("Revenue per product per market (NGN):")
print(revenue)
print()

# Total revenue per market
total_per_market = revenue.sum(axis=0)
print("Total revenue per market:")
for market, total in zip(markets, total_per_market):
    print(f"{market:8s}: ₦{total:,}")
print()

# Total revenue per product
total_per_product = revenue.sum(axis=1)
print("Total revenue per product:")
for product, total in zip(products, total_per_product):
    print(f"{product:8s}: ₦{total:,}")
print()

print(f"Grand total revenue: ₦{revenue.sum():,}")

## 9. Practical Exercise: Generate Sample Data

**Task:** Create a synthetic dataset for Nigerian market analysis.

Generate:
1. 30 days of price data for 5 products
2. Prices should follow realistic patterns (normal distribution)
3. Calculate weekly averages
4. Find days when any product exceeded ₦300

In [ ]:
# Your code here
# Hint: Use np.random.normal() for realistic price distributions

# Solution (don't peek until you try!)

In [ ]:
# SOLUTION

np.random.seed(42)

# Generate 30 days of prices for 5 products
# Each product has different mean and std
products = ['Tomato', 'Onion', 'Pepper', 'Rice', 'Beans']
price_means = [220, 280, 380, 470, 350]
price_stds = [30, 25, 40, 35, 30]

# Create 2D array: 30 days x 5 products
price_data = np.zeros((30, 5))
for i, (mean, std) in enumerate(zip(price_means, price_stds)):
    price_data[:, i] = np.random.normal(mean, std, size=30)

print("Price data shape:", price_data.shape)
print("\nFirst 5 days:")
print(price_data[:5])
print()

# Calculate weekly averages (4 weeks)
weeks = price_data.reshape(4, 7, 5)  # 4 weeks x 7 days x 5 products
weekly_avg = weeks.mean(axis=1)  # Average over days dimension

print("Weekly averages:")
for week in range(4):
    print(f"\nWeek {week + 1}:")
    for product, avg_price in zip(products, weekly_avg[week]):
        print(f"  {product:8s}: ₦{avg_price:.2f}")

# Find days when any product exceeded ₦300
high_price_days = np.any(price_data > 300, axis=1)
days_with_high_prices = np.where(high_price_days)[0] + 1  # +1 for 1-indexed days

print(f"\nDays when any product exceeded ₦300: {len(days_with_high_prices)} days")
print(f"Day numbers: {days_with_high_prices}")

## Summary: Key NumPy Operations

**Array Creation:**
- `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`
- `np.random.rand()`, `np.random.randint()`, `np.random.normal()`

**Indexing:**
- Single: `arr[0]`
- Slice: `arr[1:5]`
- Boolean: `arr[arr > 100]`
- Fancy: `arr[[0, 2, 4]]`

**Operations:**
- Element-wise: `+`, `-`, `*`, `/`
- Broadcasting: scalar to array, 1D to 2D
- Matrix: `@` or `np.dot()`

**Statistics:**
- `mean()`, `median()`, `std()`, `min()`, `max()`, `sum()`
- Axis operations: `arr.mean(axis=0)` or `arr.mean(axis=1)`

**Next:** Pandas for structured data manipulation!